# Generated by Django 2.0.10 on 2019-04-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_login', models.BooleanField(default=False, verbose_name='Departmental Login Allowed')),
                ('mentor_filling', models.BooleanField(default=False, verbose_name='Mentor Information Uploading Started')),
                ('student_login', models.BooleanField(default=False, verbose_name='Student Login Allowed')),
                ('student_filling', models.BooleanField(default=False, verbose_name='Student Information Uploading Started')),
                ('Group_creation', models.BooleanField(default=False, verbose_name='Group Creation Allowed')),
                ('Group_leaders', models.BooleanField(default=False, verbose_name='Group Leaders Created')),
                ('send_request', models.BooleanField(default=False, verbose_name='Sending Requests Allowed')),
                ('choice_filling', models.BooleanField(default=False, verbose_name='Choice Filling started')),
            ],
        ),
    ]
