# Generated by Django 2.0.10 on 2019-04-04 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190404_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdirection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction', to=settings.AUTH_USER_MODEL, verbose_name='Superuser'),
        ),
    ]
