# Generated by Django 2.0.10 on 2019-04-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_userdirection_result_declared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdirection',
            name='Group_creation',
            field=models.CharField(default='False', max_length=5, verbose_name='Group Creation Allowed'),
        ),
        migrations.AlterField(
            model_name='userdirection',
            name='Group_leaders',
            field=models.CharField(default='False', max_length=5, verbose_name='Group Leaders Created'),
        ),
        migrations.AlterField(
            model_name='userdirection',
            name='choice_filling',
            field=models.CharField(default='False', max_length=5, verbose_name='Choice Filling started'),
        ),
        migrations.AlterField(
            model_name='userdirection',
            name='dep_login',
            field=models.CharField(default='False', max_length=5, verbose_name='Departmental Login Allowed'),
        ),
        migrations.AlterField(
            model_name='userdirection',
            name='mentor_filling',
            field=models.CharField(default='False', max_length=5, verbose_name='Mentor Information Uploading Started'),
        ),
        migrations.AlterField(
            model_name='userdirection',
            name='result_declared',
            field=models.CharField(default='False', max_length=5, verbose_name='Result Declared'),
        ),
        migrations.AlterField(
            model_name='userdirection',
            name='send_request',
            field=models.CharField(default='False', max_length=5, verbose_name='Sending Requests Allowed'),
        ),
        migrations.AlterField(
            model_name='userdirection',
            name='student_filling',
            field=models.CharField(default='False', max_length=5, verbose_name='Student Information Uploading Started'),
        ),
        migrations.AlterField(
            model_name='userdirection',
            name='student_login',
            field=models.CharField(default='False', max_length=5, verbose_name='Student Login Allowed'),
        ),
    ]
