# Generated by Django 2.0.10 on 2019-04-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20190405_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='students.Student'),
        ),
    ]
