# Generated by Django 2.0.10 on 2019-04-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20190405_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprequest',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'group__isnull': True, 'leader': False}, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='students.Student', verbose_name='To'),
        ),
    ]
