# Generated by Django 2.0.10 on 2019-04-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20190405_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='group_allotted',
            field=models.IntegerField(default=0, verbose_name='Groups alloted'),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Professor', verbose_name='Mentor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='group',
            field=models.IntegerField(default=0, verbose_name='Number of Groups to be alloted'),
        ),
    ]
