# Generated by Django 2.0.10 on 2019-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20190410_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Strength in on group'),
        ),
    ]
