# Generated by Django 2.0.10 on 2019-04-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20190410_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateGroup',
        ),
    ]
