# Generated by Django 2.0.10 on 2019-04-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_delete_creategroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='qual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Qualifications'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='aoi',
            field=models.CharField(max_length=50, verbose_name='Areas Of Interest'),
        ),
    ]
