# Generated by Django 2.0.10 on 2019-04-12 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20190413_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdirection',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Superuser'),
        ),
    ]
