# Generated by Django 2.0.10 on 2019-04-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20190413_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='avg_cpi',
            field=models.BooleanField(default=False, verbose_name='Average CPI of Group'),
        ),
        migrations.AddField(
            model_name='department',
            name='leader_cpi',
            field=models.BooleanField(default=True, verbose_name='CPI of Group leader'),
        ),
    ]
