# Generated by Django 2.0.10 on 2019-04-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20190413_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='avg_cpi',
        ),
        migrations.RemoveField(
            model_name='department',
            name='leader_cpi',
        ),
    ]
