# Generated by Django 2.0.10 on 2019-04-14 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(default='No Subject', max_length=50, verbose_name='Subject')),
                ('content', models.CharField(max_length=1500, verbose_name='Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Created')),
                ('seen', models.BooleanField(default=False, verbose_name='Message Seen')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='auth.Group', verbose_name='Write message')),
            ],
        ),
    ]
