# Generated by Django 2.0.10 on 2019-04-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'group_isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='students.Student'),
        ),
    ]
