# Generated by Django 2.0.10 on 2019-04-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0002_auto_20190405_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'group__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='students.Student', verbose_name='To'),
        ),
    ]
