# Generated by Django 2.0.10 on 2019-04-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0003_auto_20190405_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Message Seen'),
        ),
    ]
