# Generated by Django 2.0.10 on 2019-04-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0005_auto_20190407_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
