# Generated by Django 2.0.10 on 2019-04-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0006_remove_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='No Subject', max_length=50, verbose_name='Subject'),
        ),
    ]
