# Generated by Django 2.0.10 on 2019-04-03 19:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('nid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Notification ID')),
                ('heading', models.CharField(max_length=40, verbose_name='Notification Heading')),
                ('detail', models.CharField(max_length=150, verbose_name='Details')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
            ],
        ),
    ]
